title: QuickOrder
description: A lightweight MVP designed to showcase a streamlined client order management system.
show_downloads: true
remote_theme: jekyll-theme-dark@latest
plugins:
  - jekyll-remote-theme
  - jekyll-spaceship
assets:
  css:
    - /assets/css/custom.css
  js:
    - /assets/js/custom.js
